import type { TextureLayer } from '@/types/Textures'

export const defaultLayerProperties: Record<TextureLayer['type'], Partial<TextureLayer>> = {
  circle: {
    type: 'circle',
    color: '#FFFFFF',
    x: 32,
    y: 32,
    radius: 16,
    visible: true,
  },
  rect: {
    type: 'rect',
    color: '#FFFFFF',
    x: 0,
    y: 0,
    width: 32,
    height: 32,
    visible: true,
  },
  line: {
    type: 'line',
    color: '#FFFFFF',
    x: 0,
    y: 0,
    x2: 64,
    y2: 64,
    lineWidth: 2,
    visible: true,
  },
  gradient: {
    type: 'gradient',
    colorStart: '#FFFFFF',
    colorEnd: '#000000',
    direction: 'vertical',
    x: 0,
    y: 0,
    width: 64,
    height: 64,
    visible: true,
  },
  pattern: {
    type: 'pattern',
    color1: '#FFFFFF',
    color2: '#CCCCCC',
    patternType: 'checkerboard',
    x: 0,
    y: 0,
    width: 64,
    height: 64,
    visible: true,
  },
  ellipse: {
    type: 'ellipse',
    color: '#FFFFFF',
    x: 32,
    y: 32,
    width: 40,
    height: 20,
    visible: true,
  },
  polygon: {
    type: 'polygon',
    color: '#FFFFFF',
    points: [
      [10, 10],
      [50, 10],
      [30, 50],
    ],
    lineWidth: 0,
    visible: true,
  },
  path: {
    type: 'path',
    color: '#FFFFFF',
    path: 'M10 10 L50 10 L30 50 Z',
    fill: true,
    lineWidth: 0,
    visible: true,
  },
}
